import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quiz app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=' bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-300'>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
